config/routes.rb
Rails.application.routes.draw do

  resources :places
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get "/auth/:action/callback", controller: "authentications", constraints: { action: /memair/ }
  end

  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user

  auto_strip_attributes :name, squish: true

  validates :name, presence: true, uniqueness: { scope: :user_id, message: "Each place should have a unique name", case_sensitive: false }
  validates :distance,  numericality: { greater_than_or_equal_to: 10 }
  validates :latitude,  numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }

  acts_as_mappable default_units: :kms, lat_column_name: :latitude, lng_column_name: :longitude, distance_field_name: :distance

  end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :revoke_token

  has_many :places, dependent: :delete_all

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:memair]

  validates :latest_latitude, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }, allow_nil: true
  validates :latest_longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  after_create :update_latest_location

  def self.from_memair_omniauth(omniauth_info)
    data        = omniauth_info.info
    credentials = omniauth_info.credentials

    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        email:    data['email'],
        password: Devise.friendly_token[0,20],
        memair_access_token: credentials['token']
      )
    end

    user.memair_access_token = credentials['token']
    user.time_zone = data['time_zone']
    user.save
    user
  end

  def get_locations_last_7_days
    user = Memair.new(self.memair_access_token)
    query = 'query{Locations(from_timestamp: "last 7 days" to_timestamp: "today" first: 10000 order_by: timestamp order: asc){timestamp lat lon}}'
    user.query(query)['data']['Locations']
  end

  def get_latest_location
    user = Memair.new(self.memair_access_token)
    query = 'query{Locations(order: desc order_by: timestamp first: 1){timestamp lat lon}}'
    user.query(query)['data']['Locations']&.first
  end

  def update_latest_location
    latest_location = get_latest_location
    if latest_location
      self.latest_latitude  = latest_location['lat']
      self.latest_longitude = latest_location['lon']
    end
  end
  
  private
    def revoke_token
      user = Memair.new(self.memair_access_token)
      query = 'mutation {RevokeAccessToken{revoked}}'
      user.query(query)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def correct_user
    klass = params['controller'].classify.constantize
    record = klass.find_by_id(params['id'])
    unless record.nil?
      @user = record.user
      redirect_to(root_url) unless current_user == @user
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update, :show, :destroy]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = current_user.places.build(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to root_path, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude, :user_id, :distance)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :flash_notice

  def home
  end

  def flash_notice
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def memair
    @user = User.from_memair_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in(:user, @user)
      flash[:notice] = 'Successfully logged'
      redirect_to root_path
    else
      session['devise.memair_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
      case level.to_sym
        when :notice then "alert alert-primary"
        when :success then "alert alert-success"
        when :error then "alert alert-danger"
        when :alert then "alert alert-warning"
      end
    end
  end
  

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_footer.html.erb
<%= stylesheet_link_tag "sticky-footer" %>

<footer class="footer">
  <div class="float-left">
    <%= link_to "Contact", 'https://blog.memair.com/community/contact', class: "nav-link" %>
  </div>
  <div class="float-right">
    <%= link_to "By memair", 'https://memair.com', class: "nav-link" %></a>
  </div>
</footer>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geo Insights</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">

    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=' + ENV['GOOGLE_MAPS_API'].to_s %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
</head>
<meta name="apple-mobile-web-app-capable" content="yes"></head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/places/_form.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMap2);

        function initMap2() {
          var lat = document.getElementById('place_latitude').value;
          var lng = document.getElementById('place_longitude').value;
          
          // if not defined create default position
          if (!lat || !lng){
              lat=<%= current_user.latest_latitude || 45.4 %>
              lng=<%= current_user.latest_longitude || -75.7 %>;
              document.getElementById('place_latitude').value = lat;
              document.getElementById('place_longitude').value = lng;
          }
          var myCoords = new google.maps.LatLng(lat, lng);
          var mapOptions = {
          center: myCoords,
          zoom: 14
          };

          var map = new google.maps.Map(document.getElementById('map2'), mapOptions);
          var marker = new google.maps.Marker({
              position: myCoords,
              animation: google.maps.Animation.DROP,
              map: map,
              draggable: true
          });
          
          // refresh marker position and recenter map on marker
          function refreshMarker(){
              var lat = document.getElementById('place_latitude').value;
              var lng = document.getElementById('place_longitude').value;
              var myCoords = new google.maps.LatLng(lat, lng);
              marker.setPosition(myCoords);
              map.setCenter(marker.getPosition());   
          }

          // when input values change call refreshMarker
          document.getElementById('place_latitude').onchange = refreshMarker;
          document.getElementById('place_longitude').onchange = refreshMarker;

          // when marker is dragged update input values
          marker.addListener('drag', function() {
              latlng = marker.getPosition();
              newlat=(Math.round(latlng.lat()*1000000))/1000000;
              newlng=(Math.round(latlng.lng()*1000000))/1000000;
              document.getElementById('place_latitude').value = newlat;
              document.getElementById('place_longitude').value = newlng;
          });

          // When drag ends, center (pan) the map on the marker position
          marker.addListener('dragend', function() {
              map.panTo(marker.getPosition());   
          });
      }
    </script>
<% end %>

<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_field :distance %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <p>
    <div id="map2" style="width:100%;"></div>
  </p>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>
<p><br></p>
<%= link_to 'Show', @place, class: "btn btn-primary" %>
<%= link_to 'Cancel', root_path, class: "btn btn-secondary" %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= place.distance %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Cancel', root_path, class: "btn btn-secondary" %>

app/views/places/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=@place.latitude%>, <%=@place.longitude%>)
    });
  </script>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @place.distance %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
    <div id="map" style="width:100%;"></div>
</p>

<%= link_to 'Edit', edit_place_path(@place), class: "btn btn-info" %>
<%= link_to 'New', new_place_path, class: "btn btn-primary" %>
<%= link_to 'Destroy', @place, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<%= link_to 'Back', root_path, class: "btn btn-secondary" %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <center>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>
  <h1>Geo Insights</h1>
  <img src="/geo-insights.png" width="25%">
  <h2>Generates insights into your movement behaviours</h2>
  <% if user_signed_in? %>
    <% if current_user.places.empty? %>
      <h3>Start by adding some places</h3>
    <% else %>
      <h3>View your latest insights in <a href="https://memair.com/insights">Memair</a></h3>
      <h4>Places</h4>
      <table>
        <tbody>
          <% current_user.places.each do |place| %>
            <tr>
              <td><%= place.name %></td>
              <td><%= link_to 'Show', place, class: "btn btn-sm btn-primary" %></td>
              <td><%= link_to 'Edit', edit_place_path(place), class: "btn btn-sm btn-info" %></td>
              <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure you want to delete this place?' }, class: "btn btn-sm btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    
    <div class="btn-group">
      <%= link_to 'Add New Place', new_place_path, class: "btn btn-primary", style: "margin: 13px;"%>
      <%= button_to "Uninstall this app", registration_path(current_user), style: "margin: 13px;", data: { confirm: 'Geo Insights will no longer generate insights in Memair.', title: 'Are you sure you?' }, method: :delete, class: "btn btn-danger" %>
    </div>
  <% else %>
    <%= button_to "Connect with Memair", user_memair_omniauth_authorize_path, id: "sign_in", class: "btn btn-lg btn-primary" %>
  <% end %>
  </center>
</div>

<script>
  if(window.location.hash == '#install') {
    document.getElementById('sign_in').click()
  }
</script>